const APP = "resume-uploader";

export const RESUME_UPLOAD_STARTED = `${APP}/RESUME_UPLOAD_STARTED`;
export const RESUME_UPLOAD_SUCCESS = `${APP}/RESUME_UPLOAD_SUCCESS`;
export const RESUME_UPLOAD_FAILED = `${APP}/RESUME_UPLOAD_FAILED`;

export const FETCH_RESUMES_STARTED = `${APP}/FETCH_RESUMES_STARTED`;
export const FETCH_RESUMES_SUCCESS = `${APP}/FETCH_RESUMES_SUCCESS`;
export const FETCH_RESUMES_FAILED = `${APP}/FETCH_RESUMES_FAILED`;
